namespace HardwareSim.Core;

/// <summary>Tracks which authored inputs and derived artifacts require recompilation or resimulation.</summary>
public sealed class ProjectDirtyState
{
    /// <summary>Gets whether the HardwareGraph has changed since the last successful compilation.</summary>
    public bool HardwareGraphDirty { get; private set; }
    /// <summary>Gets whether workload input has changed since the last successful compilation.</summary>
    public bool WorkloadGraphDirty { get; private set; }
    /// <summary>Gets whether workload-to-hardware mapping has changed.</summary>
    public bool MappingDirty { get; private set; }
    /// <summary>Gets whether physical placement has changed.</summary>
    public bool PlacementDirty { get; private set; }
    /// <summary>Gets whether physical or logical routing has changed.</summary>
    public bool RoutingDirty { get; private set; }
    /// <summary>Gets whether a device-model binding has changed.</summary>
    public bool ModelBindingDirty { get; private set; }
    /// <summary>Gets whether the compiled SimulationGraph must be rebuilt.</summary>
    public bool SimulationGraphDirty { get; private set; }
   /// <summary>Gets whether trace and metrics must be regenerated by simulation.</summary>
   public bool TraceDirty { get; private set; }
    /// <summary>Gets whether visual metadata changed without affecting simulation semantics.</summary>
    public bool VisualMetadataDirty { get; private set; }

    /// <summary>Marks HardwareGraph input dirty and invalidates compilation and trace outputs.</summary>
    public void MarkHardwareGraphChanged()
    {
        HardwareGraphDirty = true;
        InvalidateSimulationGraph();
    }

    /// <summary>Marks workload input dirty and invalidates compilation and trace outputs.</summary>
    public void MarkWorkloadGraphChanged()
    {
        WorkloadGraphDirty = true;
        InvalidateSimulationGraph();
    }

    /// <summary>Marks mapping input dirty and invalidates compilation and trace outputs.</summary>
    public void MarkMappingChanged()
    {
        MappingDirty = true;
        InvalidateSimulationGraph();
    }

    /// <summary>Marks placement input dirty and invalidates compilation and trace outputs.</summary>
    public void MarkPlacementChanged()
    {
        PlacementDirty = true;
        InvalidateSimulationGraph();
    }

    /// <summary>Marks routing input dirty and invalidates compilation and trace outputs.</summary>
    public void MarkRoutingChanged()
    {
        RoutingDirty = true;
        InvalidateSimulationGraph();
    }

    /// <summary>Marks model bindings dirty and invalidates compilation and trace outputs.</summary>
    public void MarkModelBindingChanged()
    {
        ModelBindingDirty = true;
        InvalidateSimulationGraph();
    }

    /// <summary>Clears compiler-input dirty flags while marking trace output stale.</summary>
    public void MarkCompilationSucceeded()
    {
        HardwareGraphDirty = false;
        WorkloadGraphDirty = false;
        MappingDirty = false;
        PlacementDirty = false;
        RoutingDirty = false;
        ModelBindingDirty = false;
        SimulationGraphDirty = false;
        TraceDirty = true;
    }

    /// <summary>Preserves the need to compile and simulate after a failed compilation.</summary>
    public void MarkCompilationFailed()
    {
        SimulationGraphDirty = true;
        TraceDirty = true;
    }

    /// <summary>Marks trace and metrics current after a successful simulation.</summary>
    public void MarkSimulationSucceeded() => TraceDirty = false;

    /// <summary>Marks visual metadata dirty without invalidating compilation or simulation outputs.</summary>
    public void MarkVisualMetadataChanged() => VisualMetadataDirty = true;

    /// <summary>Clears the visual-metadata dirty flag after the editor persisted visual state.</summary>
    public void ClearVisualMetadataDirty() => VisualMetadataDirty = false;

    private void InvalidateSimulationGraph()
    {
        SimulationGraphDirty = true;
        TraceDirty = true;
    }
}
